### ISSUE TITLE
Add paper

### ISSUE THREAD

**Issue by YerbaPage** [IAAR-Shanghai/ICSFSurvey#6]
Hello,

Thank you for maintaining such a wonderful repository. It’s been an excellent resource! 

Could you consider including MGDebugger [[arXiv]](https://arxiv.org/abs/2410.01215)[[repo]](https://github.com/YerbaPage/MGDebugger), which is the first hierarchical method on iteratively refining LLM-generated code? I hope MGDebugger will fit well in the "Refining the Response Iteratively" section, and it would be a great honor to have our work in this repository.

Thanks in advance for your consideration! Once again, thank you for providing such an insightful and comprehensive resource.

**Comment by Ki-Seki** [comment]
This is a very appropriate article. Thanks for sharing, I'll add it soon!

**Comment by YerbaPage** [comment]
Appreciate your warm response and support 🔥!
